name: osky
favicon: null
layout_spectrum: 0.09173438185825944
typography_spectrum: 0.8167123831808567
title: 'Film '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.33223111485131085
  lightness: 0.3246410202700645
  saturation: 0.18360333144664764
  rhythmicContrast: 0.2846269647125155
purpose: []
