name: osky
favicon: null
layout_spectrum: 0.37353
typography_spectrum: 0.3726843118201941
title: '"Reality is a dirty word to me - there''s too much of it about"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd0047'
    - '#4800fd'
    - '#ae0a37'
    - '#1b006e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
