name: osky
favicon: null
layout_spectrum: 0.37353
typography_spectrum: 0.3726843118201941
title: '"Reality is a dirty word to me - there''s too much of it about"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe0000'
    - '#fb0100'
    - '#fe0003'
    - '#c10d4e'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
