typography_spectrum: 0.16542137460783124
color:
  brandColors:
    - '#000000'
    - '#fd0047'
    - '#4800fd'
    - '#ae0a37'
    - '#1b006e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7526468350552022
analytics:
  google: null
  facebook: null
  twitter: null
name: osky
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: '"Reality is a dirty word to me - there''s too much of it about"'
description: Official Website of Film Director Oskar Kirk Hansen
purpose: []
