name: osky
favicon: null
layout_spectrum: 0.6661226057913154
typography_spectrum: 0.3726843118201941
title: 'Film '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.61564323422499
  lightness: 0.9313266319222748
  saturation: 0.8724044673144817
  rhythmicContrast: 0.46138993790373206
purpose: []
