name: osky
favicon: null
layout_spectrum: 0.6661226057913154
typography_spectrum: 0.3726843118201941
title: "\"Reality is a dirty word to me - there's too much of it about\""
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.61564323422499
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
