name: osky
favicon: null
layout_spectrum: 0.24489
typography_spectrum: 0.11407
title: '"Reality is a dirty word to me - there''s too much of it about"'
description: Official Website of Film Director Oskar Kirk Hansen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd0047'
    - '#4800fd'
    - '#ae0a37'
    - '#1b006e'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
