name: osky
favicon: null
layout_spectrum: 0.9429169446229935
typography_spectrum: 0.9822363583371043
title: 'Film '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7493005469441414
  lightness: 0.11488865106366575
  saturation: 0.5542603288777173
  rhythmicContrast: 0.3439916104543954
purpose: []
